In [1]:
#import libraries
import numpy as np

In [25]:
arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [27]:
#Excercises
#1.Create an array with numbers from 0 to 5.
arr = np.array([0,1,2,3,4,5])
#2.Print the length and shape of the array.
print(len(arr))
print(arr.shape)

6
(6,)


In [49]:
# Creating arrays
print('range:')
print(np.arange(0,10,2)) # range
print('zeros:')
print(np.zeros((2,3))) # zeros
print('ones: ')
print(np.ones((3,3))) #ones
print('random values : ') 
print(np.random.rand(2,4)) # random values

range:
[0 2 4 6 8]
zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
ones: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
random values : 
[[0.70374396 0.93627408 0.86731765 0.36673146]
 [0.05162375 0.60970207 0.03682765 0.73831483]]


In [57]:
#Exercises
#1.Create a 5×5 random matrix.
arr = np.random.rand(5,5)
#2.Create a 4×4 identity matrix.
arr_i = np.ones((4,4))
print(f'random matrix:\n{arr}\nidentity matrix:\n{arr_i}')

random matrix:
[[0.42755118 0.08559    0.68980548 0.63486171 0.64610914]
 [0.84533971 0.66603259 0.82754725 0.96618249 0.65651722]
 [0.21057399 0.23094161 0.6639038  0.68502566 0.94876056]
 [0.98985075 0.94286564 0.2874108  0.53460967 0.29064051]
 [0.03918774 0.62047129 0.52960643 0.70985569 0.88143388]]
identity matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [65]:
#Reshaping Arrays
arr = np.arange(12)
arr_reshape = arr.reshape(3,4)
print(arr)
print('reshape array:')
print(arr_reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [75]:
#Indexing & Slicing
a = np.arange(10) #a=[0,1,2,3,4,5,6,7,8,9]
print(a[2:7]) # slicing
print(a[-1]) # last element

mat = np.arange(25).reshape(5,5)
print(mat[0, :]) # first row
print(mat[:, 2]) # third column

[2 3 4 5 6]
9
[0 1 2 3 4]
[ 2  7 12 17 22]


In [105]:
# Exercises
#1.Extract the second column of a 5×5 matrix.
arr = np.arange(25).reshape((5,5))
print(arr,'\n')
print(arr[:,1,],'\n')
#2.Select all numbers greater than 10.
print(arr[2:,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[ 1  6 11 16 21] 

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [107]:
# Math Operation
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a + b)
print(a * b)
print(np.sqrt(a))

[11 22 33]
[10 40 90]
[3.16227766 4.47213595 5.47722558]


In [145]:
# Statistics
arr = np.random.randn(1000)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

-0.02144909879168683
-0.06179223881555126
0.9780901829934786
0.9566604060682166
-3.210626749919118
3.0262686289978387


In [129]:
# Excersies
#1.Create an array [1, 2, 3, 4, 5] and calculate the natural log of each element.
arr = np.array([1,2,3,4,5])
arr_ln = np.log(arr)
print(arr_ln)
#2.Generate 100 random numbers and compute mean, variance, and standard deviation.
arr_rand = np.random.rand(100)
mean_of_numbers = np.mean(arr_rand)
variance_of_numbers = np.var(arr_rand)
std_of_numbers = np.std(arr_rand)
print(f'Mean:{mean_of_numbers}\nVariance:{variance_of_numbers}\nStandard deviation:{std_of_numbers}')

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
Mean:0.5032197071624032
Variance:0.08728409066622309
Standard deviation:0.29543881035880015


In [161]:
#Matrix operations
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A, B)) #matrix multiplication
print(A @ B) #alternative syntax
print(np.linalg.det(A)) #determinant
print(np.linalg.inv(A)) # inverse of matrix
print(A.T) #

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 3]
 [2 4]]
